### ISSUE TITLE
Improve contribution guide by adding env variables

### ISSUE THREAD

**Issue by tpayet** [meilisearch/landing#373]
When trying to contribute to the project, I faced an error when following the contributing guide. I could not launch the project using `yarn build` because I was missing the necessary environment variables `NEXT_PUBLIC_DEMO_MOVIES_HOST` & `NEXT_PUBLIC_DEMO_MOVIES_API_KEY`.

Should we disclose them in contributing guide or in the README since those are public tokens? Or should we just display a warning for contributors to get those keys before trying setting up the project?

**Comment by mdubus** [comment]
Hello @tpayet 

Those environment variables are used for the Interactive Search to fetch and display the movies on the home page:
<img width="571" alt="Capture d’écran 2022-06-21 à 16 07 18" src="https://user-images.githubusercontent.com/30866152/174819909-7108b870-a20e-42c3-98ce-ff4d0fd0001d.png">

You should have a `.env.example` in the repository with those env variables, you can rename it to `.env` and replace the values with `http://localhost:7700` and `masterKey` (there is currently an issue by not providing any value, it's related to the demo-movies being in v0.24 on the Cloud && an older version of Instant Meilisearch, I will work on it later). it should work this way 👍

Let me know if it fixes the issue!
I will edit the contributing in order to explain this step better, so thanks for your feedback 🙏

**Comment by mdubus** [comment]
These should have been fixed by now, but for an unknown reason, this isn't working even by upgrading the demo-movies to v0.28 and Instant Meilisearch to the latest available version 🤔
In order to fix it, I suggest a quick fix, which I explained in another issue.
I'm therefore closing this in favor of #461
