### ISSUE TITLE
Design the new `About us` page

### ISSUE THREAD

**Issue by mdubus** [meilisearch/landing#380]
The new page will have the following blocks : 
- Hero
- Team members
- Values
- History
- Investors
- Benefits
- Opened positions / CTA to join us

**Comment by mdubus** [comment]
## Debrief with @lpinot (29/06/2022)

**Hero block:** 
- Should we keep this sentence as the Hero block, or should we change it to something else? @mdubus 

**Team members:**
- Tests should be made on the cards, to find the right balance between info and design @lpinot 
- The link could point to the public Notion page of every team member as it is more "human" than a Linkedin page (+ it has the location of everyone) @lpinot 
- The pain point would be the photos of everybody. Ideally, we would need everybody's picture with a white or green background @mdubus 
- We should avoid having a carousel as some profiles would be highlighted when others would be hidden. Everybody should be on an equal footing @lpinot 

**Values**
- Do we want paragraphs? Small sentences? How do we want our values to be represented? @mdubus 

**History**
- We talked about having:
  - A timeline with the important dates (fundraisings, Cloud release, ...) 
  - A speech from the co-founders

Should we keep both? @lpinot 

**Benefits**
- How many Perks & Benefits do we want to have max.? We would need at least the titles @mdubus 

**Opened positions**
- Check if they are easy to retrieve from Lever, and which info we can get @mdubus 
- Make the design @lpinot

**Comment by mdubus** [comment]
💡 The list of the missing information has been sent to the people involved on the 5th of July 2022

**Comment by morganeff** [comment]
**Hero block**
For lack of a better idea, I think key numbers and a small presentation text is ok for now. For key numbers: 

- the date of creation of the company: `end of 2018` instead of `4 years old`
- the number of team members: 30
- the amount of funds we have raised up to here (2 rounds of funding, 7M USD total)

The presentation text we have for Meilisearch (present in job ads) is enough for now. I'll work on an update in the months to come.

**Team**
- `Our team` vs. `Our Marvelous Team`
- Adding links to each team member's public Notion page is 👍
- Photos: ideally we would like to have an “official” individual photo for everyone. This will happen by batch, on the occasion of an offsite or other reunion. We will hire a photographer. In the meantime a personal picture will be asked for each person. Either their LinkedIn picture or any other they feel comfortable with being publicly displayed. 

**Remote working**
I'd like to add a specific section about this, as it's embedded in our culture and way of working. I'd like to add this text, please let me know what you think:

```
When you join Meilisearch you are free to come to our Paris office, or work remotely. 80% of us are working remotely today. Here's what you need to know:
- Most of us in France, some of us are in Europe and other parts of the world (Middle East, Africa, South America).
- We’re 100% ok with international hires. Our only condition is for you to share at least 4 hours of work with the France time zone (CET).
- If you are an international hire, you will either have a contractor agreement with us, or a local employment contract through a PEO (Oyster HR).
- We are learning to work asynchronously. It’s not perfect yet, but we’re getting there. The tools we use are:
    - GitHub for code & project management
    - Notion for collaborative working and team work spaces
    - Slack for instant messaging
    - Zoom, Google Meet or Around for calls
    - Figma for design
- As a remote hire, you will have access to the [[Fleex](https://en.fleex.com/)](https://en.fleex.com/) platform (Europe) or a stipend for your home office equipment.
- We reimburse up to 500$/month for co working spaces.
```

**Values**
I like having a small phrase + a short paragraph for each value:

## Commitment

### We are passionate about what we do

At Meilisearch we all do what we do because it's what we love doing. We try to keep a healthy balance between work and passion.

### We care about the project

we are all very committed to making Meilisearch a successful project, which goes beyond our individual job scopes

### We disagree and commit

For us being committed also means being opinionated and therefore disagreeing. Often. About a lot of things. We try to do this in a constructive way that helps us move forward. 

## Quality & simplicity

### We prefer quality over rapidity

Building an open-source project means respecting certain standards and paying close attention to the work we produce and show. We would rather be rigorous than rapid.

### We are pragmatic

We believe that **aiming for perfection is counterproductive.** We stand by the adage "done well today is better than perfect next week".

## Openness

### We give back to open-source what it gave to us

We are providing a high-quality search solution, accessible to all, no matter their financial means. We take pride in building a great solution thanks to the feedback of our community. 

We want to put sharing and collaboration at the basis of what we do. 

### We find solutions together

One thing we know for sure is that no one knows everything. We are constantly learning from others and are not afraid to say, "I don't know"

### We value diverse views and backgrounds

Meilisearch was built thanks to each team member's personality, skills, and experience. We are interested in welcoming people from diverse backgrounds, cultures, and opinions as we believe it is the only way to build a long-lasting company.

**Benefits**

- [4 day work week](https://blog.meilisearch.com/how-we-implemented-the-4-day-work-week/)
- Stock options
- Well being program:
    - [Mental well being](https://blog.meilisearch.com/our-first-steps-to-support-the-mental-health-of-our-team-members/): 6 coaching and mental health care sessions per year
    - Physical well being: access to [[Gymlib](https://gymlib.com/en/employee-offer)](https://gymlib.com/en/employee-offer) or reimbursement of 60€/month (equipment, classes, gym membership…).
- 3 months fully paid parental leave for birth givers *and* second parents, no matter where you are in the world,
- 6 weeks paid time off.

**Open positions**
A link towards our Lever page seems sufficient.

**Comment by morganeff** [comment]
### Photographer
The person we have hired is a freelancer, who works for Welcome to the Jungle and who did our pictures for the last version of our company page. We will ask him to bring the equipment necessary to the headshots. 

### Benefits text display
😎 [**[4 day work week](https://blog.meilisearch.com/how-we-implemented-the-4-day-work-week/)**](https://blog.meilisearch.com/how-we-implemented-the-4-day-work-week/)
No meetings or Slack messages on Fridays; you’re free to work, or not.

📈 **Stock options**
We offer stock options to all team members with long term contracts.

🧘 **Well-being program**
We offer solutions to support team members with their physical and [[mental](https://blog.meilisearch.com/our-first-steps-to-support-the-mental-health-of-our-team-members/)](https://blog.meilisearch.com/our-first-steps-to-support-the-mental-health-of-our-team-members/) well-being.

🏝 **Time off**
We offer 6 weeks of paid time off per year. 

👶 **Parental leave**
Birth givers and second parents can take a fully paid leave of 3 months to take care of their new born child.

🩺 **Health insurance**
We offer health insurance options for all team members.

**Comment by mdubus** [comment]
## Meeting with @lpinot and @morganeff (19th of September)

Morgane N. validated the designs. A photograph also came on the 20th of September to take shots of (almost) everybody. 
If someone doesn't want to have his face on the page, we could replace it with an emoji of his choice.

### What remains to do

We considered adding a carousel with pictures of the whole team. 
The Investors block should also evolve to welcome more and more investors for the future :) 

### Next steps

Léna will now decline the designs for other devices (mobile + tablet), and the development phase should start soon after.

**Comment by mdubus** [comment]
**25th October**

Beginning of the development phase.
